version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    depends_on:
      - redis
      
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"